// 与后端 constants/errorCodes 对齐；新增错误码时两侧同步
export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  ASSET_NOT_FOUND: "ASSET_NOT_FOUND",
  FAULT_NOT_FOUND: "FAULT_NOT_FOUND",
  CREW_NOT_FOUND: "CREW_NOT_FOUND",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_ALREADY_DISPATCHED: "TICKET_ALREADY_DISPATCHED",
  FAULT_ALREADY_LINKED: "FAULT_ALREADY_LINKED",
  FAULT_DUPLICATED: "FAULT_DUPLICATED",
  SKILL_NOT_MATCHED: "SKILL_NOT_MATCHED",
  CREW_OFF_DUTY: "CREW_OFF_DUTY",
  CREW_BUSY: "CREW_BUSY",
  NO_AVAILABLE_CREW: "NO_AVAILABLE_CREW",
  TICKET_STATUS_CONFLICT: "TICKET_STATUS_CONFLICT",
  INVALID_TRANSITION: "INVALID_TRANSITION"
} as const;
