export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  ASSET_NOT_FOUND: "ASSET_NOT_FOUND",
  FAULT_NOT_FOUND: "FAULT_NOT_FOUND",
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  CREW_NOT_FOUND: "CREW_NOT_FOUND",
  FAULT_ALREADY_DISPATCHED: "FAULT_ALREADY_DISPATCHED",
  CREW_OFF_DUTY: "CREW_OFF_DUTY",
  CREW_SKILL_MISMATCH: "CREW_SKILL_MISMATCH",
  CREW_BUSY: "CREW_BUSY",
  NO_AVAILABLE_CREW: "NO_AVAILABLE_CREW",
  TICKET_NOT_RESTORABLE: "TICKET_NOT_RESTORABLE",
  INVALID_TICKET_TRANSITION: "INVALID_TICKET_TRANSITION"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
